repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  # tidy up extra whitespace at end of files
  - id: trailing-whitespace
  # ensure consistent newline endings for files (\n only)
  - id: end-of-file-fixer
  # fix newlines in general to prevent pesky windows users writing CRLF
  - id: mixed-line-ending
    args:
      - --fix=lf
  # do not allow pdb/breakpoint statements to be checked in
  - id: debug-statements
  # fed up of YAML breaking
  - id: check-yaml
    args:
      - --allow-multiple-documents
  # organise requirment files alphabetically
  - id: requirements-txt-fixer
    args:
      - requirements/requirements.txt
      - requirements/requirements-dev.txt
# run flake8
- repo: git://github.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      args:
        - --max-line-length=120
        # Make flake8 ignore black's opinions
        # E126 - continuation line over-indented for hanging indent
        # E203 - whitespace before ':'
        # E501 - line too long
        # W503 - line break before binary operator
        # E231 - missing whitespace after ','
        - --ignore=E126,E203,E501,W503,E231
# run the (very opinionated!) black code formatter - https://github.com/ambv/black
- repo: git://github.com/ambv/black
  rev: 19.10b0
  hooks:
    - id: black
      args:
        - --line-length=120
        - --safe
